### ISSUE TITLE
Test case 'CodeSanity - Avoid roles ending with "_user"' fails on Xanadu

### ISSUE THREAD

**Issue by logrhythmic** [saschawildgrube/servicenow-codesanity#36]
This test case fails on a fresh Xanadu PDI.

Steps to reproduce: 
- provision fresh Xanadu PDI (glide-xanadu-07-02-2024__patch1-08-24-2024)
- install devtools
- install codesanity
- run 'CodeSanity' test suite
- note failed test case 'CodeSanity - Avoid roles ending with "_user"'
- note Summary field:

TEST CASE: Check: "CodeSanity - Avoid roles ending with "_user""
on Record: sys_user_role: 5289484c83c95210406a6f80ceaad3c2: ""
Input:
["bDetailed"]: false
["strCheckSysId"]: 5c20732b1b85e1105b76777d8b4bcb18
["strRecordSysId"]: 5289484c83c95210406a6f80ceaad3c2
["strTable"]: sys_user_role
Expected: false
Runtime: 3428 ms
Result:
0389c84c83c95210406a6f80ceaad338:
["checks"]:
___["5c20732b1b85e1105b76777d8b4bcb18"]:
______["name"]: CodeSanity - Avoid roles ending with "_user"
["sys_id"]: 0389c84c83c95210406a6f80ceaad338
Test case PASSED

TEST CASE: Check: "CodeSanity - Avoid roles ending with "_user""
on Record: sys_user_role: 9f89c84c83c95210406a6f80ceaad3ac: ""
Input:
["bDetailed"]: false
["strCheckSysId"]: 5c20732b1b85e1105b76777d8b4bcb18
["strRecordSysId"]: 9f89c84c83c95210406a6f80ceaad3ac
["strTable"]: sys_user_role
Expected: true
Runtime: 686 ms
Result:
5389c84c83c95210406a6f80ceaad3fd:
["checks"]:
___["5c20732b1b85e1105b76777d8b4bcb18"]:
______["name"]: CodeSanity - Avoid roles ending with "_user"
["sys_id"]: 5389c84c83c95210406a6f80ceaad3fd
Test case FAILED

Full logging from step execution:
11:23:16.782 Loading script: jasmine_lib/jasmine31.js
11:23:16.786 Successfully loaded jasmine_lib/jasmine31.js
11:23:17.53 Starting cache flush
11:23:17.60 Flushing the whole cache list
11:23:17.237 Loaded the Data Lookup cache in 10 ms
11:23:17.257 *** Activity.ActivityDocumentTableRepo *** com.glide.activity.core.repo.ActivityDocumentTableRepo_cache_rebuild=[]
11:23:17.264 Flushing Scoped caches
11:23:17.264 Loading properties from DB
11:23:17.406 Cache flush complete
11:23:17.407 Loading properties from DB
11:23:17.562 Slow business rule 'Properties change' on sys_properties:<span class = "session-log-bold-text"> devtools.atf.unspecified.running</span>, time was: 0:00:00.510
11:23:21.57 MetadataCustomizationEngine: entry being deleted from sys_update_xml : sys_user_role_5289484c83c95210406a6f80ceaad3c2
11:23:21.861 MetadataCustomizationEngine: entry being deleted from sys_update_xml : sys_user_role_9f89c84c83c95210406a6f80ceaad3ac

**Comment by saschawildgrube** [comment]
@logrhythmic can you confirm?

**Comment by saschawildgrube** [comment]
FYI: the same can be observed down to Vancouver.

**Comment by logrhythmic** [comment]
> @logrhythmic can you confirm?

Yes, I re-ran them and they all passed.  TY!
